# Setup
title:               Campion
tagline:             'Blogs'
description:         Forbidden safety.
url:                 https://pinqian77.github.io
baseurl:             ''
paginate:            5
paginate_path:       '/blogs/page:num'
permalink:           pretty
timezone:            Europe/London

# About/contact
author:
  name:              Pin Qian
  url:               https://twitter.com/pinqian77
  email:             pinqian77@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

version: 1.0

minima:
  date_format: "%b %-d, %Y"

theme: minima